language: ruby
sudo: false
install: 
  gem install jekyll jekyll-feed jekyll-paginate  jekyll-gist
script: jekyll build
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: $S3_BUCKET
  local_dir: _site
  region: ap-south-1
  skip_cleanup: true
  on:
    repo: sketchmemoirorg/sketchmemoirorg.github.io
